---
title: "Win Rate Convergence Analysis"
author: "Joe Stoica"
date: \today
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Win Rate Convergences

## Purpose

* Find the cutoff point for when we can stop using the bayes estimator for map
win rate and instead use the actual win rate. This also might become defunct if
more years are included in the data.

## Ideas

* Compare win rate at game *x* to the final win rate and measure epsilon. 

## TODOs

# Analysis

```{r data in}
team_list <- readRDS("data/team_list.Rdata")
```

```{r}
# This is a subfunction that cummulatively calculates the win rate of a single
# team on a single map. 
# Called in lapply.
map_win_rate <- function(map_df, team) {
    map_df$count = 1:nrow(map_df)
    map_df$wins = cumsum(map_df$outcome)
    map_df$team = team
    map_df$win_rate = map_df$wins / map_df$count
    return(map_df)
}

# Split/apply/combine strategy to get the map win rates of *one* team.
# Used in lapply
get_win_rates <- function(team) {
    to_split_df = data.frame(map = team$maps, outcome = team$match_history) 
    split_df = split(to_split_df, to_split_df$map) # split on map
    split_win_rate = lapply(split_df, map_win_rate, team = team$name)
    combined = do.call(rbind, split_win_rate)
    return(combined)
}
``` 

```{r}
# Get all of the win rates for every team on every map
all_teams_win_rate <- lapply(team_list, get_win_rates)

# Combine all of the dataframes
all_teams_win_rate <- do.call(rbind, all_teams_win_rate)
``` 

```{r}
all_teams_win_rate %>% 
    filter(map != "Cobblestone") %>% 
    ggplot(aes(count, win_rate, group = team))+
    geom_path(alpha = 0.1)+
    theme_minimal()+
    facet_wrap(.~map)+
    labs(x = "Game Count",
         y = "Win Rate")+
    geom_hline(yintercept = 0.5, color = "red")+
    scale_x_continuous(breaks = seq(0,100,20))
```


